//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AuthenticateIMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Approver
    {
        public int id { get; set; }
        public string mine_number { get; set; }
        public string department { get; set; }
        public int rights_ID { get; set; }
    
        public virtual Approval_Rights Approval_Rights { get; set; }
        public virtual Employee_Details Employee_Details { get; set; }
    }
}
