//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AuthenticateIMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Receipt
    {
        public int id { get; set; }
        public string receipt_ID { get; set; }
        public string stock_code { get; set; }
        public int quantity { get; set; }
        public string units { get; set; }
        public string acceptor { get; set; }
        public System.DateTime date_of_receipt { get; set; }
        public string compartment_ID { get; set; }
        public string stock_type { get; set; }
        public Nullable<System.DateTime> expiry_date { get; set; }
        public string category_ID { get; set; }
        public string comment { get; set; }
    
        public virtual Employee_Details Employee_Details { get; set; }
        public virtual Stock_Details Stock_Details { get; set; }
    }
}
