//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AuthenticateIMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Request_Details
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Request_Details()
        {
            this.Approvals = new HashSet<Approval>();
            this.Rejects = new HashSet<Reject>();
        }
    
        public int id { get; set; }
        public string request_ID { get; set; }
        public string stock_code { get; set; }
        public string compartment_ID { get; set; }
        public string purpose_of_item { get; set; }
        public string mine_number { get; set; }
        public System.DateTime date_of_request { get; set; }
        public int quantity { get; set; }
        public string unit_of_issue { get; set; }
        public Nullable<int> approval_status { get; set; }
        public string approver { get; set; }
        public string comment { get; set; }
        public Nullable<System.DateTime> expected_date { get; set; }
        public Nullable<int> workflow_ID { get; set; }
    
        public virtual Approval_Status Approval_Status1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Approval> Approvals { get; set; }
        public virtual Employee_Details Employee_Details { get; set; }
        public virtual Stock_Details Stock_Details { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Reject> Rejects { get; set; }
    }
}
