//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AuthenticateIMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Workflow
    {
        public int id { get; set; }
        public int workflow_ID { get; set; }
        public string workflow_description { get; set; }
        public string mine_number { get; set; }
        public string comment { get; set; }
    }
}
